// UI dictionary — client-safe (no server imports).
// Arabic-first; English covers the full public browsing surface.
// User-generated content (listing titles/descriptions) stays as written.

export type Lang = "ar" | "en";

const ar = {
  nav: {
    postAd: "أضف إعلان",
    login: "دخول",
    signup: "حساب جديد",
    auctions: "المزادات",
    all: "الكل",
    searchPh: "وش تدور؟ سيارات، عقارات، جوالات...",
    home: "الرئيسية",
    listings: "الإعلانات",
    account: "حسابي",
    notifications: "الإشعارات",
  },
  menu: {
    dashboard: "لوحة التحكم",
    myListings: "إعلاناتي",
    messages: "الرسائل",
    verifications: "التحققات",
    favorites: "المفضلة",
    notifications: "الإشعارات",
    settings: "إعدادات الحساب",
    admin: "لوحة الإدارة",
    logout: "تسجيل الخروج",
    points: "نقطة",
  },
  home: {
    browseCategories: "تصفح الفئات",
    viewAll: "عرض الكل",
    liveNow: "مزادات جارية الحين",
    liveSub: "سُم بهوية مقنّعة — وآخر سومة قبل الإغلاق تمدد الوقت تلقائياً",
    live: "مباشر",
    promoted: "مُختار لك",
    sponsored: "ممول",
    featured: "إعلانات مميزة",
    latest: "أحدث الإعلانات",
    browseAll: "تصفح جميع الإعلانات",
    noLive: "ما فيه مزادات جارية حالياً.",
    statListings: "إعلان نشط",
    statAuctions: "مزاد مباشر",
    statUsers: "مستخدم موثوق",
  },
  card: {
    featured: "مميز",
    live: "مباشر",
    ended: "انتهى",
    endsIn: "ينتهي خلال",
    negotiable: "على السوم",
    day: "يوم",
    conditions: { NEW: "جديد", LIKE_NEW: "كالجديد", USED: "مستعمل" } as Record<string, string>,
  },
  auctionsPage: {
    title: "المزادات المباشرة",
    subtitle:
      "سُم بخصوصية تامة — هويات المزايدين مخفية، وأي سومة في آخر دقيقتين تمدد المزاد تلقائياً لضمان العدالة",
    liveNow: "مزاد مباشر الحين",
    endedRecently: "انتهت مؤخراً",
    emptyTitle: "ما فيه مزادات جارية حالياً",
    emptyHint: "كن أول من يفتح مزاد — أضف إعلانك واختر «مزاد»",
    statLive: "مزاد مباشر",
    statEndingSoon: "ينتهي خلال ساعة",
    statEnded: "انتهت مؤخراً",
    statBids: "مزايدة مباشرة",
    sortEnding: "الأقرب للانتهاء",
    sortBids: "الأكثر مزايدات",
    sortPriceHigh: "أعلى سومة",
    sortPriceLow: "أقل سومة",
    searchPlaceholder: "ابحث في المزادات…",
    quickAll: "كل المزادات",
    quickEndingSoon: "تنتهي خلال ساعة",
    quickBuyNow: "فيها شراء فوري",
    resultsCount: "مزاد مباشر",
    clearFilters: "مسح الفلاتر",
    liveSection: "المزادات المباشرة",
  },
  listingsPage: {
    title: "تصفح الإعلانات",
    resultsFor: "نتائج البحث عن",
    adsCount: "إعلان",
    browseInCategory: "تصفح في الفئة:",
    emptyTitle: "ما لقينا نتائج مطابقة",
    emptyHint: "جرّب تعدل الفلاتر أو تدور بكلمات ثانية",
    prev: "السابق",
    next: "التالي",
    pageOf: (p: number, t: number) => `صفحة ${p} من ${t}`,
  },
  categoryPage: {
    home: "الرئيسية",
    categories: "الفئات",
    activeAds: "إعلان نشط",
    allCategories: "جميع الفئات",
    emptyTitle: "ما فيه إعلانات في هذي الفئة للحين",
    emptyHint: "كن أول من يعلن هنا",
    addYourAd: "أضف إعلانك",
  },
  filters: {
    allCities: "كل المدن",
    bothTypes: "بيع ومزاد",
    standard: "بيع عادي",
    auction: "مزاد",
    allConditions: "كل الحالات",
    priceFrom: "السعر من",
    priceTo: "السعر إلى",
    sortNew: "الأحدث",
    sortPriceAsc: "السعر: من الأقل",
    sortPriceDesc: "السعر: من الأعلى",
    sortViews: "الأكثر مشاهدة",
    apply: "تطبيق",
    label: "الفلاتر",
    show: "عرض",
    hide: "إخفاء",
  },
  detail: {
    description: "الوصف",
    productDetails: "تفاصيل المنتج",
    auctionTerms: "شروط المزاد",
    views: "مشاهدة",
    published: "نُشر",
    chatSeller: "مراسلة البائع",
    favorite: "المفضلة",
    inFavorites: "في المفضلة",
    report: "إبلاغ",
    similar: "إعلانات مشابهة",
    safetyTitle: "إرشادات حراج ستيشن للأمان قبل الشراء:",
    safety: [
      "قابل البائع في مكان عام وآمن ومضاء، ولا تذهب وحدك إن أمكن.",
      "افحص المنتج وتأكد من مطابقته للإعلان قبل الدفع أو المغادرة.",
      "لا تشارك بياناتك البنكية أو أي أكواد تحقق أو معلومات حساسة مع أي طرف.",
      "ألغِ الصفقة فوراً إذا ظهرت أي مؤشرات مريبة أو طلبات غير طبيعية.",
    ],
    safetyFooter: "حراج ستيشن منصة وسيطة فقط ولا تتحمل مسؤولية جودة المنتج أو سلامة الصفقة.",
    delivery: { PICKUP: "استلام يدوي (مقابلة)", SHIPPING: "شحن", DELIVERY: "توصيل" } as Record<string, string>,
    privacyNote:
      "خصوصية المزايدين: الأسماء تُعرض بهوية مقنّعة، وبيانات المزايدين الحقيقية محفوظة ومحمية داخل النظام ولا يطّلع عليها إلا ضمن الصلاحيات المسموح بها.",
  },
  seller: {
    info: "معلومات البائع",
    memberSince: "عضو منذ",
    deals: "معاملة ناجحة",
    whatsapp: "واتساب",
    call: "اتصال",
  },
  bid: {
    live: "مزاد مباشر",
    ended: "انتهى المزاد",
    bids: "سومة",
    current: "السوم الحالي",
    finalPrice: "السعر النهائي",
    timeLeft: "الوقت المتبقي",
    winner: "الفائز",
    youTop: "سومك هو الأعلى حالياً",
    yourAuction: "هذا مزادك — ما تقدر تسوم عليه",
    bidNow: "زايد الحين",
    minBid: "أقل سوم مقبول:",
    buyNow: "شراء فوري",
    loginToBid: "سجّل دخولك عشان تسوم",
    history: "سجل السوم",
    noBids: "ما فيه سوم للحين — كن أول من يسوم",
    you: "أنت",
    accepted: "تم قبول سومك بنجاح",
    extended: "قبلنا سومك — وتمدد المزاد دقيقتين (حماية من القنص)",
    boughtNow: "مبروك! تم الشراء الفوري",
    failed: "ما تمت السومة، حاول مرة ثانية",
    buyNowConfirm: (price: string) => `تبي الشراء الفوري بـ${price}؟ المزاد بيقفل على طول.`,
    proxyTitle: "المزايدة بالوكالة",
    proxyHint: "حط حدك الأعلى والنظام يزايد عنك تلقائياً بأقل زيادة ممكنة — حدّك يظل سرياً",
    proxyPlaceholder: "حدك الأعلى",
    proxySet: "فعّل الوكالة",
    proxyUpdate: "حدّث حدك",
    proxyActive: (max: string) => `الوكالة مفعّلة — حدك الأعلى ${max}`,
    proxyCancel: "إلغاء الوكالة",
    proxyDoneTop: "تم! النظام يزايد عنك وأنت الأعلى حالياً",
    proxyDoneOutbid: "حدك الأعلى أقل من مزايد آخر — ارفع حدك أو زايد يدوياً",
    proxyCancelConfirm: "إلغاء المزايدة بالوكالة؟ سومك الحالي يظل ملزماً.",
  },
  comments: {
    title: "الاستفسارات والتعليقات",
    seller: "البائع",
    placeholder: "وش ودك تعرف عن السلعة؟ اسأل هنا...",
    note: "التعليقات عامة ويشوفها الجميع — لا تشارك أرقاماً أو بيانات حساسة هنا.",
    loginPrompt: "عشان تسأل عن هذا الإعلان",
    loginLink: "سجّل دخولك",
  },
  footer: {
    tagline:
      "سوقك السعودي الأول للمزادات والإعلانات المبوبة. بيع واشترِ بثقة وشفافية مع نظام المصداقية المتبادل.",
    market: "السوق",
    liveAuctions: "المزادات الجارية",
    latestAds: "أحدث الإعلانات",
    allCategories: "جميع الفئات",
    postYourAd: "أضف إعلانك",
    trending: "فئات رائجة",
    vehicles: "سيارات ومركبات",
    realestate: "عقارات",
    electronics: "إلكترونيات",
    animals: "حيوانات",
    samel: "حراج ستيشن",
    pro: "حساب برو",
    trust: "نظام المصداقية",
    terms: "الشروط والأحكام",
    privacy: "سياسة الخصوصية",
    contact: "تواصل معنا",
    safety: "تعامل بأمان: قابل في مكان عام، وافحص قبل الدفع، ولا تشارك بياناتك البنكية",
    rights: "جميع الحقوق محفوظة",
    disclaimer: "حراج ستيشن منصة إعلانات ومزادات فقط، ولا تتدخل في التعاملات المالية بين البائع والمشتري.",
  },
  auth: {
    loginTitle: "تسجيل الدخول",
    loginSub: "حياك الله من جديد في حراج ستيشن",
    identifier: "البريد الإلكتروني أو رقم الجوال",
    password: "كلمة المرور",
    forgot: "نسيت كلمة المرور؟",
    loginBtn: "دخول",
    noAccount: "ليس لديك حساب؟",
    registerNow: "سجّل الآن",
    demoAccounts: "حسابات تجريبية:",
    registerTitle: "حساب جديد",
    registerSub: "حياك في حراج ستيشن — انضم لآلاف البائعين والمشترين",
    fullName: "الاسم الكامل",
    email: "البريد الإلكتروني",
    city: "المدينة",
    passwordHint: "8 أحرف على الأقل",
    termsAgree: "أوافق على",
    termsLink: "الشروط والأحكام",
    termsRest: "وأقر بأن حراج ستيشن منصة وسيطة غير مسؤولة عن التعاملات بين المستخدمين",
    phoneNote:
      "يمكنك إضافة رقم جوالك لاحقاً من إعدادات الحساب — وسيُستخدم مستقبلاً لتوثيق حسابك عند الإجراءات الحساسة.",
    createBtn: "إنشاء الحساب",
    haveAccount: "لديك حساب بالفعل؟",
    loginLink: "سجّل دخولك",
    genericError: "حدث خطأ، حاول مرة أخرى",
  },
  forgot: {
    title: "نسيت كلمة المرور؟",
    sub: "أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة تعيين كلمة المرور",
    sent: "إذا كان البريد مسجلاً لدينا فستصلك رسالة تحتوي رابط إعادة التعيين.",
    demoNote: "الوضع التجريبي — إرسال البريد قيد الربط، استخدم الرابط مباشرة:",
    resetNow: "إعادة تعيين كلمة المرور الآن",
    backToLogin: "العودة لتسجيل الدخول",
    email: "البريد الإلكتروني",
    sendBtn: "إرسال رابط إعادة التعيين",
    remembered: "تذكرت كلمة المرور؟",
    loginLink: "سجّل دخولك",
    resetTitle: "تعيين كلمة مرور جديدة",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور",
    passwordHint: "8 أحرف على الأقل",
    mismatch: "كلمتا المرور غير متطابقتين",
    saveBtn: "حفظ كلمة المرور",
    resetDone: "تم تغيير كلمة المرور بنجاح.",
    loginWithNew: "تسجيل الدخول بكلمة المرور الجديدة",
  },
  contact: {
    title: "تواصل معنا",
    sub: "فريق دعم حراج ستيشن جاهز لمساعدتك في أي استفسار أو مشكلة",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    whatsapp: "واتساب الأعمال",
    hours: "ساعات العمل:",
  },
  profile: {
    memberSince: "عضو منذ",
    deals: "معاملة ناجحة",
    verified: "موثّق",
    verifiedTip: "هوية موثّقة من إدارة المنصة",
    reviews: "تقييم",
    activeListings: "الإعلانات النشطة",
    reviewsTitle: "التقييمات",
    noListings: "لا توجد إعلانات نشطة حالياً",
    noReviews: "لا توجد تقييمات بعد",
    credScore: "نقاط المصداقية",
    listingsOf: (name: string) => `إعلانات ${name}`,
  },
};

const en: typeof ar = {
  nav: {
    postAd: "Post Ad",
    login: "Login",
    signup: "Sign up",
    auctions: "Auctions",
    all: "All",
    searchPh: "Search cars, real estate, phones...",
    home: "Home",
    listings: "Listings",
    account: "Account",
    notifications: "Notifications",
  },
  menu: {
    dashboard: "Dashboard",
    myListings: "My Listings",
    messages: "Messages",
    verifications: "Verifications",
    favorites: "Favorites",
    notifications: "Notifications",
    settings: "Account Settings",
    admin: "Admin Panel",
    logout: "Log out",
    points: "pts",
  },
  home: {
    browseCategories: "Browse Categories",
    viewAll: "View all",
    liveNow: "Live Auctions",
    liveSub: "Bid with a masked identity — last-minute bids extend the timer automatically",
    live: "LIVE",
    promoted: "Picked for You",
    sponsored: "Sponsored",
    featured: "Featured Listings",
    latest: "Latest Listings",
    browseAll: "Browse all listings",
    noLive: "No live auctions right now.",
    statListings: "active listings",
    statAuctions: "live auctions",
    statUsers: "trusted users",
  },
  card: {
    featured: "Featured",
    live: "LIVE",
    ended: "Ended",
    endsIn: "Ends in",
    negotiable: "Negotiable",
    day: "d",
    conditions: { NEW: "New", LIKE_NEW: "Like New", USED: "Used" },
  },
  auctionsPage: {
    title: "Live Auctions",
    subtitle:
      "Bid with full privacy — bidder identities are masked, and last-two-minute bids extend the auction automatically for fairness",
    liveNow: "live auctions now",
    endedRecently: "Recently ended",
    emptyTitle: "No live auctions right now",
    emptyHint: "Be the first — post your listing and choose “Auction”",
    statLive: "Live auctions",
    statEndingSoon: "Ending within an hour",
    statEnded: "Recently ended",
    statBids: "Live bids",
    sortEnding: "Ending soonest",
    sortBids: "Most bids",
    sortPriceHigh: "Highest bid",
    sortPriceLow: "Lowest bid",
    searchPlaceholder: "Search auctions…",
    quickAll: "All auctions",
    quickEndingSoon: "Ending within an hour",
    quickBuyNow: "With buy-now",
    resultsCount: "live auctions",
    clearFilters: "Clear filters",
    liveSection: "Live auctions",
  },
  listingsPage: {
    title: "Browse Listings",
    resultsFor: "Results for",
    adsCount: "listings",
    browseInCategory: "Browse in category:",
    emptyTitle: "No matching results",
    emptyHint: "Try adjusting the filters or different keywords",
    prev: "Previous",
    next: "Next",
    pageOf: (p: number, t: number) => `Page ${p} of ${t}`,
  },
  categoryPage: {
    home: "Home",
    categories: "Categories",
    activeAds: "active listings",
    allCategories: "All Categories",
    emptyTitle: "No listings in this category yet",
    emptyHint: "Be the first to post here",
    addYourAd: "Post your ad",
  },
  filters: {
    allCities: "All cities",
    bothTypes: "Sale & auction",
    standard: "Standard sale",
    auction: "Auction",
    allConditions: "All conditions",
    priceFrom: "Price from",
    priceTo: "Price to",
    sortNew: "Newest",
    sortPriceAsc: "Price: low to high",
    sortPriceDesc: "Price: high to low",
    sortViews: "Most viewed",
    apply: "Apply",
    label: "Filters",
    show: "Show",
    hide: "Hide",
  },
  detail: {
    description: "Description",
    productDetails: "Product Details",
    auctionTerms: "Auction Terms",
    views: "views",
    published: "Posted",
    chatSeller: "Chat with seller",
    favorite: "Favorite",
    inFavorites: "Saved",
    report: "Report",
    similar: "Similar Listings",
    safetyTitle: "Haraj Station safety tips before you buy:",
    safety: [
      "Meet the seller in a public, safe, well-lit place — bring someone if you can.",
      "Inspect the item and verify it matches the listing before paying or leaving.",
      "Never share bank details, verification codes, or sensitive info with anyone.",
      "Cancel the deal immediately if anything feels suspicious.",
    ],
    safetyFooter: "Haraj Station is a marketplace only and bears no responsibility for product quality or deal safety.",
    delivery: { PICKUP: "Local pickup", SHIPPING: "Shipping", DELIVERY: "Delivery" },
    privacyNote:
      "Bidder privacy: names are shown masked. Real bidder data is stored securely and accessible only under authorized permissions.",
  },
  seller: {
    info: "Seller Info",
    memberSince: "Member since",
    deals: "successful deals",
    whatsapp: "WhatsApp",
    call: "Call",
  },
  bid: {
    live: "Live Auction",
    ended: "Auction Ended",
    bids: "bids",
    current: "Current Bid",
    finalPrice: "Final Price",
    timeLeft: "Time Remaining",
    winner: "Winner",
    youTop: "You are the highest bidder",
    yourAuction: "This is your auction — you can't bid on it",
    bidNow: "Bid Now",
    minBid: "Minimum bid:",
    buyNow: "Buy Now",
    loginToBid: "Log in to bid",
    history: "Bid History",
    noBids: "No bids yet — be the first",
    you: "You",
    accepted: "Your bid was accepted",
    extended: "Bid accepted — auction extended by 2 minutes (anti-sniping)",
    boughtNow: "Congratulations! Purchase complete",
    failed: "Bid failed, try again",
    buyNowConfirm: (price: string) => `Buy now for ${price}? The auction will close immediately.`,
    proxyTitle: "Proxy Bidding",
    proxyHint: "Set your maximum and the system bids for you with the smallest possible increments — your ceiling stays private",
    proxyPlaceholder: "Your maximum",
    proxySet: "Enable proxy",
    proxyUpdate: "Update maximum",
    proxyActive: (max: string) => `Proxy active — your maximum is ${max}`,
    proxyCancel: "Cancel proxy",
    proxyDoneTop: "Done! The system bids for you and you're currently on top",
    proxyDoneOutbid: "Your maximum is below another bidder's — raise it or bid manually",
    proxyCancelConfirm: "Cancel proxy bidding? Your current bid remains binding.",
  },
  comments: {
    title: "Questions & Comments",
    seller: "Seller",
    placeholder: "Ask about this item...",
    note: "Comments are public — don't share numbers or sensitive info here.",
    loginPrompt: "to ask about this listing",
    loginLink: "Log in",
  },
  footer: {
    tagline:
      "Saudi Arabia's first marketplace for auctions and classifieds. Buy and sell with confidence through mutual credibility.",
    market: "Marketplace",
    liveAuctions: "Live Auctions",
    latestAds: "Latest Listings",
    allCategories: "All Categories",
    postYourAd: "Post Your Ad",
    trending: "Trending",
    vehicles: "Vehicles",
    realestate: "Real Estate",
    electronics: "Electronics",
    animals: "Pets & Animals",
    samel: "Haraj Station",
    pro: "Pro Account",
    trust: "Credibility System",
    terms: "Terms & Conditions",
    privacy: "Privacy Policy",
    contact: "Contact Us",
    safety: "Stay safe: meet in public, inspect before paying, never share bank details",
    rights: "All rights reserved",
    disclaimer: "Haraj Station is a classifieds & auctions platform only and is not involved in payments between buyers and sellers.",
  },
  auth: {
    loginTitle: "Log in",
    loginSub: "Welcome back to Haraj Station",
    identifier: "Email or phone number",
    password: "Password",
    forgot: "Forgot password?",
    loginBtn: "Log in",
    noAccount: "Don't have an account?",
    registerNow: "Sign up",
    demoAccounts: "Demo accounts:",
    registerTitle: "Create Account",
    registerSub: "Join thousands of buyers and sellers on Haraj Station",
    fullName: "Full name",
    email: "Email",
    city: "City",
    passwordHint: "At least 8 characters",
    termsAgree: "I agree to the",
    termsLink: "Terms & Conditions",
    termsRest: "and acknowledge Haraj Station is an intermediary platform not responsible for user transactions",
    phoneNote:
      "You can add your phone number later in account settings — it will be used for verification of sensitive actions.",
    createBtn: "Create account",
    haveAccount: "Already have an account?",
    loginLink: "Log in",
    genericError: "Something went wrong, try again",
  },
  forgot: {
    title: "Forgot your password?",
    sub: "Enter your email and we'll send you a password-reset link",
    sent: "If this email is registered with us, you'll receive a message with the reset link.",
    demoNote: "Demo mode — email delivery is being connected, use the link directly:",
    resetNow: "Reset password now",
    backToLogin: "Back to login",
    email: "Email",
    sendBtn: "Send reset link",
    remembered: "Remembered your password?",
    loginLink: "Log in",
    resetTitle: "Set a new password",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    passwordHint: "At least 8 characters",
    mismatch: "Passwords don't match",
    saveBtn: "Save password",
    resetDone: "Your password was changed successfully.",
    loginWithNew: "Log in with your new password",
  },
  contact: {
    title: "Contact Us",
    sub: "The Haraj Station support team is ready to help with any question or issue",
    email: "Email",
    phone: "Phone",
    whatsapp: "Business WhatsApp",
    hours: "Working hours:",
  },
  profile: {
    memberSince: "Member since",
    deals: "successful deals",
    verified: "Verified",
    verifiedTip: "Identity verified by the platform",
    reviews: "reviews",
    activeListings: "Active Listings",
    reviewsTitle: "Reviews",
    noListings: "No active listings right now",
    noReviews: "No reviews yet",
    credScore: "Credibility Score",
    listingsOf: (name: string) => `Listings by ${name}`,
  },
};

export const DICT: Record<Lang, typeof ar> = { ar, en };
