ALTER TABLE "LoginOtp" ADD COLUMN "purpose" TEXT NOT NULL DEFAULT 'SITE_LOGIN',
 ADD COLUMN "sessionVersion" INTEGER NOT NULL DEFAULT -1,
 ADD COLUMN "issuedEmail" TEXT NOT NULL DEFAULT '',
 ADD COLUMN "pendingName" TEXT,
 ADD COLUMN "deliveredAt" TIMESTAMP(3);
UPDATE "LoginOtp" SET "consumedAt" = CURRENT_TIMESTAMP WHERE "consumedAt" IS NULL;
